version: "3.8"

services:
  halmos:
    build:
      context: .
      dockerfile: Dockerfile.halmos
    volumes:
      - .:/app
    working_dir: /app
    command: ["--contract", "NoahSymbolicTest", "--solver-timeout-assertion", "60000"]
