[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Solc settings
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Test settings
verbosity = 3
fuzz = { runs = 256 }

# Formatter settings
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
